### ISSUE TITLE
Illegal Reflective Access Operation to field java.net.HttpURLConnection.method

### ISSUE THREAD

**Issue by andrewlalis** [hub4j/github-api#754] opened 2020-03-25 13:28 UTC
**Describe the bug**
I attempt to archive a repository using the following code:
```java
GHRepository repo = this.org.getRepository("repo-name-here");
repo.archive();
```
When checking GitHub itself, the repository is in fact archived, however I receive a warning in the stderr stream consisting of the following:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo (file:/C:/Users/andrew/.m2/repository/org/kohsuke/github-api/1.108/github-api-1.108.jar) to field java.net.HttpURLConnection.method
WARNING: Please consider reporting this to the maintainers of org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**
1. Fetch a `GHRepository` that is not yet archived.
2. Call `archive()` on that repository.

**Expected behavior**
I expect that there should not be any illegal reflective access exceptions.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 74

**Comment by bitwiseman** [comment] 2020-03-26 22:42
This is not an exception, as you noted your action succeeded. 

If you use the JDK version of `HTTPUrlConnection`, it only allows a specific set of verbs, so we must use reflection to override that. 
https://github.com/github-api/github-api/blob/4c30f94355dfca7034f6619f64543ee3e9fcafdf/src/main/java/org/kohsuke/github/GitHubHttpUrlConnectionClient.java#L162-L191

If you switch to another implementation such as OkHttp3, this should go away. 

"All illegal access operations will be denied in a future release".

**Comment by lotharschulz** [comment] 2020-09-07 10:23
I experience the same behavior using kotlin with 

```kotlin
repository.setDefaultBranch("some-branch")
```

---

> "All illegal access operations will be denied in a future release", but as of Java 13 that has not happened yet.

I experience the same with Java 14 ( jvm target set in _build.gradle.kts_: `kotlinOptions.jvmTarget = "14"`)

**Comment by bitwiseman** [comment] 2020-09-08 08:24
@lotharschulz 
There is nothing to be done about this as long as this library uses `HttpURLConnection`. 
Have you tried using OkHttp3?

**Comment by lotharschulz** [comment] 2020-09-08 08:45
> Have you tried using OkHttp3?

Yes and wasn't successful so far. I use [GitHub.connect](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L136) to connect to GitHub.com with _[Environmental variables](https://github-api.kohsuke.org/)_.  

The code in [OkHttpConnectorTest](https://github.com/hub4j/github-api/blob/master/src/test/java/org/kohsuke/github/extras/okhttp3/OkHttpConnectorTest.java) was promising in the beginning, but I could not find a hint that made my code work.

In case it exists, please point me to an example that explains how to use `OkHttp3` with [GitHub.connect](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GitHub.java#L136) & [Environmental variables](https://github-api.kohsuke.org/).

**Comment by bitwiseman** [comment] 2020-09-09 00:18
> but I could not find a hint that made my code work. 

```java
import okhttp3.OkHttpClient;
import org.kohsuke.github.GitHubBuilder;
import org.kohsuke.github.extras.okhttp3.OkHttpConnector;

static OkHttpClient baseClient = new OkHttpClient();

GitHubBuilder.
    .fromEnvironment()
    .withConnector(new OkHttpConnector(baseClient.newBuilder().build())
    .build(); 
```

**Comment by lotharschulz** [comment] 2020-09-09 06:52
Thanks @bitwiseman! Will give that approach a try and let you know. I am on another task at the moment. I can't tell you when I am going to come back to you though.

**Comment by lotharschulz** [comment] 2020-09-22 08:36
Thanks @bitwiseman! These are the relevant kotlin changes I was able to do based on your [input](https://github.com/hub4j/github-api/issues/754#issuecomment-689204775):

additional dependency [kotlin dsl](https://docs.gradle.org/current/userguide/kotlin_dsl.html) (_build.gradle.kts_)
```kts
    implementation("com.squareup.okhttp3:okhttp:4.9.0")
```

_some kt file_
```kt
import okhttp3.OkHttpClient
import org.kohsuke.github.GitHubBuilder.fromEnvironment
import org.kohsuke.github.extras.okhttp3.OkHttpConnector
...
// within an existing class
    companion object {
        private val baseClient = OkHttpClient()
    }
...
// within an existing fun
                fromEnvironment().
                withConnector(
                    OkHttpConnector(
                        baseClient.newBuilder().build()
                    )
                ).build()
```

**Comment by aalmiray** [comment] 2021-04-07 12:54
I just hit the same issue when updating a the state of a Milestone.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo (file:/private/tmp/jreleaser/jreleaser-0.1.0-SNAPSHOT/lib/github-api-1.125.jar) to field java.net.HttpURLConnection.method
WARNING: Please consider reporting this to the maintainers of org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

As previously stated running the code in Java 8 does not produce the warning.
Running the code with Java 9 up to 15 will produce the warning.
Running the code with JAva 16+ will make the program fail as I believe illegal-access is no longer allowed.

Moving to OkHttp is not an option (at least not for me).

The OpenFeign project has the same issue with their default HttpClient (inability to support more HTTP verbs such as PATCH). They did not use reflection to fix this. Instead they offer other Http clients such as Apache HTTP Client.

Would it be possible for this project to provide another HttpConnector based on Apache Http Client?

**Comment by bitwiseman** [comment] 2021-04-08 19:04
@aalmiray 
You are welcome to implement one.  The `HttpConnector` interface depends on `HttpURLConnection` interface and is very minimal.

As an alternative it looks like you can allow reflective access in various ways: 

https://stackoverflow.com/questions/46454995/how-to-hide-warning-illegal-reflective-access-in-java-9-without-jvm-argument
https://nipafx.dev/five-command-line-options-hack-java-module-system/
https://dzone.com/articles/migrating-your-project-to-jigsaw-step-by-step

At some point we'll remove the dependency on `HttpURLConnection`, but that is a much larger effort.

**Comment by aalmiray** [comment] 2021-04-08 19:09
I might actually, considering my tool has to run with Java 8 for a loooong time.

Coincidentally, the links you posted don't work in this situation: running in classpath mode in Java 9+

The 1st link simply disables the warning. OK-ish in 9 - 15 but will break in 16+.
The other 2 links assume the application is modular, which again is not the case as the application is designed to run in the classpath.,

Hence why an alternate client is needed.

**Comment by bitwiseman** [comment] 2021-04-08 19:16
@aalmiray 
Hmm, take a look at this: 
https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch

We might be able to avoid reflection by using `X-HTTP-Method-Override` headers assuming GitHub recognizes it.  Before you go  implement an apache connector, could you give this a try? It would be a nice improvement to the project.

**Comment by aalmiray** [comment] 2021-04-08 19:43
Well I could use the header but hub4j would still use the reflective call to set the HTTP verb. I don't think there's a way from my POV as a consumer to tell if the header works or not. The real test is to remove the reflective call _and_ use the override header.

**Comment by bitwiseman** [comment] 2021-04-08 20:21
@aalmiray  I meant, you could try updating hub4j to use the header and remove the reflective access.  

Replacing this insanity:
https://github.com/hub4j/github-api/blob/7c8a7ff26ebfb31aed3bfdd8f0825ea56142ba4e/src/main/java/org/kohsuke/github/GitHubHttpUrlConnectionClient.java#L165-L189

**Comment by bitwiseman** [comment] 2021-04-08 21:50
@aalmiray 
Okay, you got me excited about removing this hacky reflection code.  See PR  #1083 .  If you could build this locally and give it try, that would a huge help.  I will probably not include this in the next release, but the release after it since this is in some respects a _huge_ change.

**Comment by aalmiray** [comment] 2021-04-08 21:52
Thank you @bitwiseman 😄 ! 
I'll give it a try tomorrow, it's close to midnight where I am right now. 
Will report back as soon as I have something conclusive.

**Comment by aalmiray** [comment] 2021-04-09 16:27
@bitwiseman I can confirm the override method works and no reflection calls occur. Thank you!

**Comment by bitwiseman** [comment] 2021-06-01 22:40
Unfortunately, `HTTP-Method-Override` only works in **most** cases. It turns out some endpoints do not honor it.

**Closed** 2021-11-21 08:32 UTC
Labels: bug, task, external

**Comment by aalmiray** [comment] 2022-08-27 14:56
Any chance of this being revisited? Sadly OkHttp is not an option for me. Apache Client would be much better. 

Closing a milestone when running on JDK17 will trigger an error because of reflective access.

**Comment by gsmet** [comment] 2022-08-27 15:01
@aalmiray are you sure? I think this has been fixed with the latest versions and the switch to the JDK11+ client.

**Comment by aalmiray** [comment] 2022-08-27 15:07
Yes, I'm sure as I can't use the JDK11+ client just yet. The code that applies `PATCH` relies on reflection and that crashes under JDK17+

**Comment by gsmet** [comment] 2022-08-27 15:18
Well, sure, if you’re not using the JDK 11 one, it will fail. I can understand the Okhttp client might not be ideal given you end up with Kotlin around but not sure why the JDK 11 client wouldn’t be. 
Your requirements look extremely specific so maybe you can use a tweaked client layer. I would have thought it would be possible given the infra work that was done.

**Comment by aalmiray** [comment] 2022-08-27 15:56
Correct. JReleaser's Maven and Gradle plugins are still bound to JDK8 for the foreseeable future. This problem becomes moot the project upgrades to JDK11.

I suppose staying with hub4j 1.2x is the current workaround.
