### ISSUE TITLE
Change to use `UncheckedIOException` and un-checked exceptions

### ISSUE THREAD

**Issue by alexec** [hub4j/github-api#1699] opened 2023-08-23 01:30 UTC
I know this is probably many changes, but it will make the code easier to use with Java streams.

I'm doing data analysis with this library, so I'm using streams extensively. You cannot throw checked exceptions in streams. What could be an elegant one liner becomes and ugly 5 line `try-catch` block.

**Comment by bitwiseman** [comment] 2023-08-24 01:22
Duplicate of #1658.  As I said there, I'm open to adding methods to support this as long as we do not make *binary* breaking changes, perhaps using bridge methods.

**Closed by bitwiseman** 2023-08-24 01:22 UTC
