### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.squareup.okhttp3:okhttp:jar

### ISSUE THREAD

**Issue by Bing-ok** [hub4j/github-api#925] opened 2020-08-15 15:13 UTC
Hi, there are multiple versions of <b><i>com.squareup.okhttp3:okhttp</i></b> in <b><i>github-api-master</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>com.squareup.okhttp3:okhttp:4.4.1</i></b> can be loaded, and <b><i>com.squareup.okhttp3:okhttp:3.12.3</i></b> will be shadowed.

As <b><i>com.squareup.okhttp3:okhttp:3.12.3</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. okhttp3.internal.Version: java.lang.String userAgent()</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection: java.io.OutputStream getOutputStream()&gt; github-api-master\target\classes
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: java.io.OutputStream getOutputStream()&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: okhttp3.Call buildCall()&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: java.lang.String defaultUserAgent()&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.Version: java.lang.String userAgent()&gt;
</details>

<b><i>2. okhttp3.internal.http.HttpDate: java.lang.String format(java.util.Date)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection: void setIfModifiedSince(long)&gt; github-api-master\target\classes
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: void setIfModifiedSince(long)&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.http.HttpDate: java.lang.String format(java.util.Date)&gt;
</details>

<b><i>3. okhttp3.internal.platform.Platform: void log(int,java.lang.String,java.lang.Throwable)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection: void setRequestProperty(java.lang.String,java.lang.String)&gt; github-api-master\target\classes
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: void setRequestProperty(java.lang.String,java.lang.String)&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.platform.Platform: void log(int,java.lang.String,java.lang.Throwable)&gt; 
</details>

<b><i>4. okhttp3.internal.http.StatusLine: okhttp3.internal.http.StatusLine get(okhttp3.Response)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection: java.lang.String getHeaderField(java.lang.String)&gt; github-api-master\target\classes
</br>&lt;okhttp3.internal.huc.OkHttpURLConnection: java.lang.String getHeaderField(java.lang.String)&gt; Repositories\com\squareup\okhttp3\okhttp-urlconnection\3.12.3\okhttp-urlconnection-3.12.3.jar
</br>&lt;okhttp3.internal.http.StatusLine: okhttp3.internal.http.StatusLine get(okhttp3.Response)&gt; 
</details>

The above missing methods are actually referenced by <b><i>github-api-master</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade dependency <b><i>com.squareup.okhttp3:okhttp-urlconnection</i></b> from <b><i>3.12.3</i></b> to <b><i>4.4.1</i></b>. Because one conflicting library version <b><i>com.squareup.okhttp3:okhttp:3.12.3</i></b> is transitively introduced by <b><i>com.squareup.okhttp3:okhttp-urlconnection:3.12.3</i></b>. Upgrading dependency <b><i>com.squareup.okhttp3:okhttp-urlconnection</i></b> from <b><i>3.12.3</i></b> to <b><i>4.4.1</i></b> can solve this dependency conflict.
2. Change dependency <b><i>com.squareup.okhttp3:okhttp</i></b> from <b><i>4.4.1</i></b> to <b><i>3.12.3</i></b>.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

Dependency tree----

<details>
<summary>click for details</summary>
</br>[INFO] org.kohsuke:github-api:jar:1.117-SNAPSHOT
</br>[INFO] +- org.apache.commons:commons-lang3:jar:3.9:compile
</br>[INFO] +- org.hamcrest:hamcrest:jar:2.2:test
</br>[INFO] +- org.hamcrest:hamcrest-core:jar:2.2:test
</br>[INFO] |  \- (org.hamcrest:hamcrest:jar:2.2:test - omitted for duplicate)
</br>[INFO] +- org.hamcrest:hamcrest-library:jar:2.2:test
</br>[INFO] |  \- (org.hamcrest:hamcrest-core:jar:2.2:test - omitted for duplicate)
</br>[INFO] +- junit:junit:jar:4.13:test
</br>[INFO] |  \- (org.hamcrest:hamcrest-core:jar:1.3:test - omitted for conflict with 2.2)
</br>[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.2:compile
</br>[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.2:compile
</br>[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.10.2:compile
</br>[INFO] +- commons-io:commons-io:jar:2.4:compile
</br>[INFO] +- com.infradna.tool:bridge-method-annotation:jar:1.18:compile
</br>[INFO] |  \- org.jenkins-ci:annotation-indexer:jar:1.4:compile
</br>[INFO] +- commons-fileupload:commons-fileupload:jar:1.4:test
</br>[INFO] |  \- (commons-io:commons-io:jar:2.2:test - omitted for conflict with 2.4)
</br>[INFO] +- commons-discovery:commons-discovery:jar:0.5:test
</br>[INFO] |  \- commons-logging:commons-logging:jar:1.1.1:test
</br>[INFO] +- org.kohsuke.stapler:stapler:jar:1.260:test
</br>[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.2:test
</br>[INFO] |  +- (commons-discovery:commons-discovery:jar:0.4:test - omitted for conflict with 0.5)
</br>[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.2:test
</br>[INFO] |  |  +- (commons-logging:commons-logging:jar:1.1.1:test - omitted for duplicate)
</br>[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.1:test
</br>[INFO] |  +- (commons-io:commons-io:jar:2.4:test - omitted for duplicate)
</br>[INFO] |  +- (commons-logging:commons-logging:jar:1.2:test - omitted for conflict with 1.1.1)
</br>[INFO] |  +- commons-codec:commons-codec:jar:1.9:test
</br>[INFO] |  +- org.jvnet.localizer:localizer:jar:1.7:test
</br>[INFO] |  +- org.kohsuke.stapler:json-lib:jar:2.4-jenkins-2:test
</br>[INFO] |  |  +- (commons-beanutils:commons-beanutils:jar:1.8.0:test - omitted for conflict with 1.9.2)
</br>[INFO] |  |  +- (commons-collections:commons-collections:jar:3.2.1:test - omitted for duplicate)
</br>[INFO] |  |  +- commons-lang:commons-lang:jar:2.5:test
</br>[INFO] |  |  +- (commons-logging:commons-logging:jar:1.1.1:test - omitted for duplicate)
</br>[INFO] |  |  \- net.sf.ezmorph:ezmorph:jar:1.0.6:test
</br>[INFO] |  |     \- (commons-lang:commons-lang:jar:2.3:test - omitted for conflict with 2.5)
</br>[INFO] |  +- org.jvnet:tiger-types:jar:2.2:test
</br>[INFO] |  +- com.google.guava:guava:jar:11.0.1:test
</br>[INFO] |  |  \- (com.google.code.findbugs:jsr305:jar:1.3.9:test - omitted for conflict with 2.0.1)
</br>[INFO] |  +- org.kohsuke:asm5:jar:5.0.1:test
</br>[INFO] |  +- (commons-fileupload:commons-fileupload:jar:1.3.1-jenkins-2:test - omitted for conflict with 1.4)
</br>[INFO] |  +- com.google.code.findbugs:jsr305:jar:2.0.1:test
</br>[INFO] |  +- com.jcraft:jzlib:jar:1.1.3:test
</br>[INFO] |  \- (com.github.spotbugs:spotbugs-annotations:jar:3.1.12:test - omitted for conflict with 4.1.1)
</br>[INFO] +- org.kohsuke.stapler:stapler-jetty:jar:1.1:test
</br>[INFO] |  +- (org.kohsuke.stapler:stapler:jar:1.177:test - omitted for conflict with 1.260)
</br>[INFO] |  \- org.eclipse.jetty:jetty-servlet:jar:7.5.4.v20111024:test
</br>[INFO] |     \- org.eclipse.jetty:jetty-security:jar:7.5.4.v20111024:test
</br>[INFO] |        \- org.eclipse.jetty:jetty-server:jar:7.5.4.v20111024:test
</br>[INFO] |           +- javax.servlet:servlet-api:jar:2.5:test
</br>[INFO] |           +- org.eclipse.jetty:jetty-continuation:jar:7.5.4.v20111024:test
</br>[INFO] |           \- org.eclipse.jetty:jetty-http:jar:7.5.4.v20111024:test
</br>[INFO] |              \- org.eclipse.jetty:jetty-io:jar:7.5.4.v20111024:test
</br>[INFO] |                 \- org.eclipse.jetty:jetty-util:jar:7.5.4.v20111024:test
</br>[INFO] +- org.eclipse.jgit:org.eclipse.jgit:jar:5.7.0.202003110725-r:test
</br>[INFO] |  +- com.jcraft:jsch:jar:0.1.55:test
</br>[INFO] |  +- (com.jcraft:jzlib:jar:1.1.1:test - omitted for conflict with 1.1.3)
</br>[INFO] |  +- com.googlecode.javaewah:JavaEWAH:jar:1.1.7:test
</br>[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.2:test
</br>[INFO] |  +- org.bouncycastle:bcpg-jdk15on:jar:1.64:test
</br>[INFO] |  |  \- (org.bouncycastle:bcprov-jdk15on:jar:1.64:test - omitted for duplicate)
</br>[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:test
</br>[INFO] |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:test
</br>[INFO] |     \- (org.bouncycastle:bcprov-jdk15on:jar:1.64:test - omitted for duplicate)
</br>[INFO] +- com.squareup.okio:okio:jar:2.5.0:compile
</br>[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.70:compile
</br>[INFO] |  |  +- (org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile - omitted for duplicate)
</br>[INFO] |  |  \- org.jetbrains:annotations:jar:13.0:compile
</br>[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile
</br>[INFO] +- <b>com.squareup.okhttp3:okhttp:jar:4.4.1:compile</b>
</br>[INFO] |  +- (com.squareup.okio:okio:jar:2.4.3:compile - omitted for conflict with 2.5.0)
</br>[INFO] |  \- (org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.61:compile - omitted for conflict with 1.3.70)
</br>[INFO] +- com.squareup.okhttp3:okhttp-urlconnection:jar:3.12.3:compile
</br>[INFO] |  \- <b>(com.squareup.okhttp3:okhttp:jar:3.12.3:compile - omitted for conflict with 4.4.1)</b>
</br>[INFO] +- com.squareup.okhttp:okhttp-urlconnection:jar:2.7.5:compile
</br>[INFO] |  \- com.squareup.okhttp:okhttp:jar:2.7.5:compile
</br>[INFO] |     \- (com.squareup.okio:okio:jar:1.6.0:compile - omitted for conflict with 2.5.0)
</br>[INFO] +- org.kohsuke:wordnet-random-name:jar:1.3:test
</br>[INFO] +- org.mockito:mockito-core:jar:3.4.6:test
</br>[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.10.13:test
</br>[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.13:test
</br>[INFO] |  \- org.objenesis:objenesis:jar:2.6:test
</br>[INFO] +- com.github.spotbugs:spotbugs-annotations:jar:4.1.1:provided
</br>[INFO] |  \- (com.google.code.findbugs:jsr305:jar:3.0.2:provided - omitted for conflict with 2.0.1)
</br>[INFO] +- com.github.tomakehurst:wiremock-jre8-standalone:jar:2.27.1:test
</br>[INFO] \- com.google.code.gson:gson:jar:2.8.6:test
</details>

**Comment by Bing-ok** [comment] 2020-08-15 15:15
Could you help me review this issue? 👍 Thanks! @bitwiseman

**Comment by bitwiseman** [comment] 2020-08-17 15:28
@Bing-ok 

> Suggested fixing solutions:
> 
> 1. Upgrade dependency com.squareup.okhttp3:okhttp-urlconnection from 3.12.3 to 4.4.1. Because one conflicting library version com.squareup.okhttp3:okhttp:3.12.3 is transitively introduced by com.squareup.okhttp3:okhttp-urlconnection:3.12.3. Upgrading dependency com.squareup.okhttp3:okhttp-urlconnection from 3.12.3 to 4.4.1 can solve this dependency conflict.
> 2. Change dependency com.squareup.okhttp3:okhttp from 4.4.1 to 3.12.3.

Neither of these. This setting is by design. 

These are optional dependencies.  `com.squareup.okhttp3:okhttp-urlconnection` is deprecated, but retained for compatibility.  

If a down stream project wants to use `com.squareup.okhttp3:okhttp-urlconnection` they can do so my forcing `com.squareup.okhttp3:okhttp` in their project to `3.12.3` (using `dependencyManagment`).

**Comment by Bing-ok** [comment] 2020-08-20 08:18
Thanks for your support!

**Comment by bitwiseman** [comment] 2020-08-20 19:37
@Bing-ok 
Dependency management allows you to `exclude` dependencies or force them to versions you want.
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-management

I assume that you are trying to use `com.squareup.okhttp3:okhttp-urlconnection`.  I strongly suggest that you use the `Client` class of `com.squareup.okhttp3:okhttp` if possible.  `com.squareup.okhttp3:okhttp-urlconnection` is deprecated and unsupported.   

Putting that aside, here's how you can fix the dependency tree problem you're seeing. 

You can do this: 
```
  <dependencies>
     <dependency>
       <groupId>com.squareup.okhttp3</groupId>
       <artifactId>okhttp-urlconnection</artifactId>
       <version>3.12.12</version>
    </dependency>
    <dependency>
      <groupId>org.kohsuke</groupId>
      <artifactId>github-api</artifactId>
      <version>1.116</version>
      <exclusions>
        <exclusion>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp-urlconnection</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
```

Or you can something like this: 
```
  <dependencyManagement>
    <dependencies>
       <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp</artifactId>
         <version>3.12.12</version>
      </dependency>
       <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp-urlconnection</artifactId>
         <version>3.12.12</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
     <dependency>
       <groupId>com.squareup.okhttp3</groupId>
       <artifactId>okhttp-urlconnection</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kohsuke</groupId>
      <artifactId>github-api</artifactId>
      <version>1.116</version>
    </dependency>
  </dependencies>
```

**Comment by bitwiseman** [comment] 2020-08-20 19:39
Closing as not an issue, but I'm happy to continue discussing as needed.  Please consider joining the gitter.im channel to ask questions.

**Closed by bitwiseman** 2020-08-20 19:39 UTC
