### ISSUE TITLE
getting org.kohsuke.github.GHIOException: Failed to set the custom verb 

### ISSUE THREAD

**Issue by abhiscrach** [hub4j/github-api#1306] opened 2021-11-20 05:06 UTC
**Describe the bug**
I am getting org.kohsuke.github.GHIOException: Failed to set the custom verb when I try following
```
 GHIssue issue = getIssue(1234);//uses repo_.getIssue(n)
if(issue !=null)
 issue.setBody("Some body string");//fails here with following error
```
JDK 15
logs
org.kohsuke.github.GHIOException: Failed to set the custom verb

	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:59)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.send(Requester.java:61)
	at org.kohsuke.github.GHIssue.edit(GHIssue.java:229)
	at org.kohsuke.github.GHIssue.setBody(GHIssue.java:284)

**Comment by bitwiseman** [comment] 2021-11-20 06:59
Duplicate of #1202

**Closed by bitwiseman** 2021-11-20 06:59 UTC
