### ISSUE TITLE
Search results do not return all results

### ISSUE THREAD

**Issue by Xterminatorz** [hub4j/github-api#1094] opened 2021-04-13 01:25 UTC
**Describe the bug**
Searching for issues does not return the full list of issues. I am trying to retrieve all issues updated after a certain date time. This is the snippet of code I'm using. The search query from the code is something like this `is:issue repo:userx/repo updated:>2021-03-01T00:00:00-08:00`.

```
LocalDateTime t = LocalDateTime.parse(time, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
String query = "is:issue repo:" + issueRepo.getFullName() + " updated:>" + OffsetDateTime.of(t, zoneId.getRules().getOffset(t)).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
PagedSearchIterable<GHIssue> searchResults = gh.searchIssues().q(query).list().withPageSize(100);
System.out.println(searchResults.getTotalCount());
issues = searchResults.toList();
System.out.println(issues.size());
```
`getTotalCount` returns 2300 results for me, but `toList` stops returning issues once page size * pages is greater than 1000 results. For example, if page size is 30, 1020 results are returned. If page size is 99, 1089 issues are returned.

**To Reproduce**
1. Query for issues that has over 1000 results

**Expected behavior**
`toList` should include all issues from the search result.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 87

**Comment by bitwiseman** [comment] 2021-04-13 16:00
In what way does it stop?  Does it just not return more results or does it throw an exception? 

Oh, also are  the result marked as incomplete?  https://docs.github.com/en/rest/reference/search#timeouts-and-incomplete-results 

This is likely a limitation of the GitHub REST API, not a bug in this library. If you take the url for your search and iterate through it with curl  commands, you will probably get the same behavior.

**Comment by Xterminatorz** [comment] 2021-04-13 19:54
It stops returning more results. Results are not marked incomplete.

You are right that it is a limitation to the GitHub REST API. They bolded that search only goes up to 1,000 results at the top on the page you linked.

Feel free to close this issue.

**Closed** 2021-04-13 20:01 UTC
Labels: external, more information needed
