### ISSUE TITLE
WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to https://api.github.com/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by soul2zimate** [hub4j/github-api#997] opened 2020-12-03 07:58 UTC
`WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to https://api.github.com/ was leaked. Did you forget to close a response body?`

I am using version 1.116. I sometimes see this warning message in my server log, there is no real occurrence pattern. I am not sure why that happened, but it seems it relates to bad network connection.

In my code, I have a static GitHub instance and use it periodically to communicate with Github.

```
    protected static GitHub github;

...
// create the github instance from initialization like below 
...

    github = new GitHubBuilder()
            .withOAuthToken(config.getPassword(), config.getUsername())
            .withConnector(new OkHttpConnector(new OkUrlFactory(new OkHttpClient().setCache(cache))))
            .build();
```
I can see similar message mentioned in a previous pull request #346 on Feb 23, 2017 trying to ignore the warning from okhttp.

Does this really a harmful messages ? How should I prevent this in github-api since I don't use okhttp directly.

Thank you.

**Comment by bitwiseman** [comment] 2020-12-04 00:09
@soul2zimate  
https://github.com/hub4j/github-api/pull/984 probably addresses this issue.  It will be in the next release.

**Comment by soul2zimate** [comment] 2020-12-04 00:47
Great! looking forward to the next release. thanks.

**Comment by bitwiseman** [comment] 2020-12-04 00:55
@soul2zimate If you want to help out, you could build the code from that PR and see if it works for your case.

**Comment by soul2zimate** [comment] 2020-12-04 02:15
sure, I will build a 1.118-SNAPSHOT and test it at the local.

**Comment by soul2zimate** [comment] 2020-12-04 02:59
`2020-12-04 10:27:55,670 WARNING [com.squareup.okhttp.OkHttpClient] (OkHttp ConnectionPool) A connection to https://api.github.com/ was leaked. Did you forget to close a response body?`

Unfortunately, it still sporadically presents in log with the fix mentioned in your 1st comment. Does is also close the response body in case of unexpected IO exception from network lag?

**Comment by bitwiseman** [comment] 2020-12-10 21:02
@soul2zimate 
There is probably a path where it does not.  This covers cases where response info is created. 

https://github.com/hub4j/github-api/blob/c06c06624d3003b1f1b2aadecff65e1298f598b7/src/main/java/org/kohsuke/github/GitHubClient.java#L425

But can totally believe there is a path through all the obsolete code that gets a body and then doesn't close it.  

https://github.com/hub4j/github-api/blob/c06c06624d3003b1f1b2aadecff65e1298f598b7/src/main/java/org/kohsuke/github/GitHubHttpUrlConnectionClient.java#L58-L72

It is also possible that some part of your code is the cause - if the caller gets a stream and doesn't close it, the leak could still happen.  Are you using any of the methods that return `InputStream`, such as `GHRepository.readBlob()`, or `GHRepository.renderMarkdown()` or `GHTreeEntry.readAsBlob()`? 

I'm laying blame just looking for possibilities. I thought we'd mostly closed the problem.

**Comment by bitwiseman** [comment] 2020-12-11 00:36
@soul2zimate 
Oh, wait.  Your output says `com.squareup.okhttp.OkHttpClient`.  Are you using `okhttp` or `okhttp3`?

**Comment by soul2zimate** [comment] 2020-12-11 03:14
Because I need to use the conditional request against GitHub, I am using okhttp as pluggable HTTP client with **okhttp-urlconnection** version 2.7.5

The way I instantiate the `GitHub` in issue description is basically as same as the last `Pluggable HTTP client` section on https://github-api.kohsuke.org/

**Comment by bitwiseman** [comment] 2020-12-12 03:30
@soul2zimate 
Try switching to okhttp3 v3.14.x.  It should be a drop in replacement if all you're doing is using URLConnection.  I'm deprecating support for 2.x.

**Closed** 2020-12-13 00:49 UTC
Labels: bug

**Comment by soul2zimate** [comment] 2020-12-15 01:12
Thanks, I have tried with okhttps, the warning seems gone.
